theme: jekyll-theme-minimal
title: Ericka Menchen-Trevino, Ph.D.
description: A mixed methods computational social scientist, methodologist, political communicaiton scholar, data collection tool creator, and (bread) baker.
